backend:
  name: git-gateway
  repo: ziro-app/jobs
  accept_roles:
    - admin
    - editor

media_folder: static/assets
public_folder: assets
display_url: https://vagas.ziro.online
slug:
  encoding: ascii
  clean_accents: true

collections:
  - name: blog
    label: Jobs
    description: Click 'New Job' to post job opening to dashboard
    folder: blog
    create: true
    extension: md
    format: frontmatter
    slug: '{{year}}-{{month}}-{{day}}_{{slug}}'
    fields:
      - { name: path, label: Path, widget: string, pattern: ['^\/', 'Deve iniciar com /'] }
      - { name: date, label: Date, widget: date }
      - { name: location, label: Location, widget: select, options: ['Remoto', 'São Paulo, SP'] }
      - { name: area, label: Area, widget: select, options: ['Operação', 'Produto'] }
      - { name: title, label: Title }
      - { name: body, label: Body, widget: markdown }